site_name: MongoLearning
site_description: Mongo 学习
repo_url: https://github.com/linupychiang/mongo-learning/
copyright: "2022, Linupy"

nav:
  - Instroduce: introduce.md
  - Install: install.md
  - Basic: basic.md
  - HelloMongo: hello-mongodb.md

theme:
  name: readthedocs
  favicon: "images/icon.png"
  logo: "images/logo.png"
